# Ghidra: annotate unpacked MightyQuest. Window>Script Manager>Run
# @category Unpacking
from ghidra.program.model.symbol import SourceType
fm=currentProgram.getFunctionManager(); st=currentProgram.getSymbolTable()
oep=toAddr(0xa545e0)
createLabel(oep,"start_WinMainCRTStartup",True)
setEOLComment(oep,"Original Entry Point (recovered)")
createLabel(toAddr(0xa545e0),"WinMainCRTStartup_OEP",True)
createLabel(toAddr(0xa67750),"__tmainCRTStartup",True)
createLabel(toAddr(0xa676d0),"__security_init_cookie",True)
createLabel(toAddr(0xdec020),"imp_RegQueryValueExA",True); setEOLComment(toAddr(0xdec020),"RegQueryValueExA")
createLabel(toAddr(0xdec070),"imp_RtlLeaveCriticalSection",True); setEOLComment(toAddr(0xdec070),"RtlLeaveCriticalSection")
createLabel(toAddr(0xdec07c),"imp_GetTickCount",True); setEOLComment(toAddr(0xdec07c),"GetTickCount")
createLabel(toAddr(0xdec0e8),"imp_ResumeThread",True); setEOLComment(toAddr(0xdec0e8),"ResumeThread")
createLabel(toAddr(0xdec10c),"imp_QueryPerformanceCounter",True); setEOLComment(toAddr(0xdec10c),"QueryPerformanceCounter")
createLabel(toAddr(0xdec148),"imp_InterlockedExchangeAdd",True); setEOLComment(toAddr(0xdec148),"InterlockedExchangeAdd")
createLabel(toAddr(0xdec14c),"imp_InterlockedCompareExchange",True); setEOLComment(toAddr(0xdec14c),"InterlockedCompareExchange")
createLabel(toAddr(0xdec150),"imp_RtlEnterCriticalSection",True); setEOLComment(toAddr(0xdec150),"RtlEnterCriticalSection")
createLabel(toAddr(0xdec190),"imp_ResetEvent",True); setEOLComment(toAddr(0xdec190),"ResetEvent")
createLabel(toAddr(0xdec1c8),"imp_CreateDirectoryA",True); setEOLComment(toAddr(0xdec1c8),"CreateDirectoryA")
createLabel(toAddr(0xdec214),"imp_GlobalFree",True); setEOLComment(toAddr(0xdec214),"GlobalFree")
createLabel(toAddr(0xdec234),"imp_Sleep",True); setEOLComment(toAddr(0xdec234),"Sleep")
createLabel(toAddr(0xdec238),"imp_WaitForSingleObject",True); setEOLComment(toAddr(0xdec238),"WaitForSingleObject")
createLabel(toAddr(0xdec23c),"imp_GetLastError",True); setEOLComment(toAddr(0xdec23c),"GetLastError")
createLabel(toAddr(0xdec268),"imp_SwitchToThread",True); setEOLComment(toAddr(0xdec268),"SwitchToThread")
createLabel(toAddr(0xdec270),"imp_GetProcessHeap",True); setEOLComment(toAddr(0xdec270),"GetProcessHeap")
createLabel(toAddr(0xdec280),"imp_CloseHandle",True); setEOLComment(toAddr(0xdec280),"CloseHandle")
createLabel(toAddr(0xdec448),"imp__acmdln",True); setEOLComment(toAddr(0xdec448),"_acmdln")
createLabel(toAddr(0xdec44c),"imp__fmode",True); setEOLComment(toAddr(0xdec44c),"_fmode")
createLabel(toAddr(0xdec450),"imp__commode",True); setEOLComment(toAddr(0xdec450),"_commode")
createLabel(toAddr(0xdec578),"imp_SysFreeString",True); setEOLComment(toAddr(0xdec578),"SysFreeString")
createLabel(toAddr(0xdec60c),"imp_SetDlgItemTextA",True); setEOLComment(toAddr(0xdec60c),"SetDlgItemTextA")
createLabel(toAddr(0xdec658),"imp_TranslateMessage",True); setEOLComment(toAddr(0xdec658),"TranslateMessage")
createLabel(toAddr(0xdec65c),"imp_DispatchMessageA",True); setEOLComment(toAddr(0xdec65c),"DispatchMessageA")
createLabel(toAddr(0xdec748),"imp_select",True); setEOLComment(toAddr(0xdec748),"select")
createLabel(toAddr(0xdec7b0),"imp__BinkOpenDirectSound@4",True); setEOLComment(toAddr(0xdec7b0),"_BinkOpenDirectSound@4")
createLabel(toAddr(0xdec898),"imp_cef_string_wide_cmp",True); setEOLComment(toAddr(0xdec898),"cef_string_wide_cmp")
createLabel(toAddr(0xdec89c),"imp_cef_string_utf16_clear",True); setEOLComment(toAddr(0xdec89c),"cef_string_utf16_clear")
createLabel(toAddr(0x10744e0),"imp_SetConsoleInputExeNameW",True); setEOLComment(toAddr(0x10744e0),"SetConsoleInputExeNameW")
createLabel(toAddr(0x1130010),"imp_RtlInitializeCriticalSection",True); setEOLComment(toAddr(0x1130010),"RtlInitializeCriticalSection")
createLabel(toAddr(0x1130014),"imp_GetModuleFileNameW",True); setEOLComment(toAddr(0x1130014),"GetModuleFileNameW")
createLabel(toAddr(0x1130028),"imp_LoadLibraryW",True); setEOLComment(toAddr(0x1130028),"LoadLibraryW")
createLabel(toAddr(0x113002c),"imp_CreateEventW",True); setEOLComment(toAddr(0x113002c),"CreateEventW")
createLabel(toAddr(0x1130030),"imp_CompareStringW",True); setEOLComment(toAddr(0x1130030),"CompareStringW")
createLabel(toAddr(0x1130038),"imp_GetModuleHandleA",True); setEOLComment(toAddr(0x1130038),"GetModuleHandleA")
createLabel(toAddr(0x113003c),"imp_VirtualProtect",True); setEOLComment(toAddr(0x113003c),"VirtualProtect")
createLabel(toAddr(0x1130054),"imp_WriteProcessMemory",True); setEOLComment(toAddr(0x1130054),"WriteProcessMemory")
createLabel(toAddr(0x1130068),"imp_OpenThread",True); setEOLComment(toAddr(0x1130068),"OpenThread")
createLabel(toAddr(0x1130074),"imp_SuspendThread",True); setEOLComment(toAddr(0x1130074),"SuspendThread")
createLabel(toAddr(0x1130078),"imp_ResumeThread",True); setEOLComment(toAddr(0x1130078),"ResumeThread")
createLabel(toAddr(0x113007c),"imp_GetSystemInfo",True); setEOLComment(toAddr(0x113007c),"GetSystemInfo")
createLabel(toAddr(0x1130080),"imp_LoadResource",True); setEOLComment(toAddr(0x1130080),"LoadResource")
createLabel(toAddr(0x1130084),"imp_MultiByteToWideChar",True); setEOLComment(toAddr(0x1130084),"MultiByteToWideChar")
createLabel(toAddr(0x113008c),"imp_FindResourceExW",True); setEOLComment(toAddr(0x113008c),"FindResourceExW")
createLabel(toAddr(0x1130090),"imp_FindResourceExA",True); setEOLComment(toAddr(0x1130090),"FindResourceExA")
createLabel(toAddr(0x1130094),"imp_GetThreadLocale",True); setEOLComment(toAddr(0x1130094),"GetThreadLocale")
createLabel(toAddr(0x1130098),"imp_GetUserDefaultLCID",True); setEOLComment(toAddr(0x1130098),"GetUserDefaultLCID")
createLabel(toAddr(0x113009c),"imp_GetSystemDefaultLCID",True); setEOLComment(toAddr(0x113009c),"GetSystemDefaultLCID")
createLabel(toAddr(0x11300a0),"imp_EnumResourceNamesA",True); setEOLComment(toAddr(0x11300a0),"EnumResourceNamesA")
createLabel(toAddr(0x11300a4),"imp_EnumResourceNamesW",True); setEOLComment(toAddr(0x11300a4),"EnumResourceNamesW")
createLabel(toAddr(0x11300a8),"imp_EnumResourceLanguagesA",True); setEOLComment(toAddr(0x11300a8),"EnumResourceLanguagesA")
createLabel(toAddr(0x11300ac),"imp_EnumResourceLanguagesW",True); setEOLComment(toAddr(0x11300ac),"EnumResourceLanguagesW")
createLabel(toAddr(0x11300b0),"imp_EnumResourceTypesA",True); setEOLComment(toAddr(0x11300b0),"EnumResourceTypesA")
createLabel(toAddr(0x11300b4),"imp_EnumResourceTypesW",True); setEOLComment(toAddr(0x11300b4),"EnumResourceTypesW")
createLabel(toAddr(0x11300b8),"imp_RtlAllocateHeap",True); setEOLComment(toAddr(0x11300b8),"RtlAllocateHeap")
createLabel(toAddr(0x11300bc),"imp_HeapFree",True); setEOLComment(toAddr(0x11300bc),"HeapFree")
createLabel(toAddr(0x11300c8),"imp_GetSystemTime",True); setEOLComment(toAddr(0x11300c8),"GetSystemTime")
createLabel(toAddr(0x11300cc),"imp_GetLocalTime",True); setEOLComment(toAddr(0x11300cc),"GetLocalTime")
createLabel(toAddr(0x11300d0),"imp_SystemTimeToFileTime",True); setEOLComment(toAddr(0x11300d0),"SystemTimeToFileTime")
createLabel(toAddr(0x11300d4),"imp_CompareFileTime",True); setEOLComment(toAddr(0x11300d4),"CompareFileTime")
createLabel(toAddr(0x11300f4),"imp_TlsGetValue",True); setEOLComment(toAddr(0x11300f4),"TlsGetValue")
createLabel(toAddr(0x11300fc),"imp_TlsSetValue",True); setEOLComment(toAddr(0x11300fc),"TlsSetValue")
createLabel(toAddr(0x1130100),"imp_TlsFree",True); setEOLComment(toAddr(0x1130100),"TlsFree")